- hosts: all
  vars_files:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"

  tasks:
  - name: Install Web Server Software
    package:
      name: "{{ package_name }}"
      state: present

  - name: "OS name and Version"
    debug:
      msg: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"

  - name: Copy webpage
    template:
      dest: "{{ doc_root }}"
      src: index.html

  - name: Start the service
    service:
      name: "{{ service_name }}"
      state: started
